### PR TITLE
[FileCommander] More refinements

### PR DESCRIPTION
**Pull request by IanSav**
- Correct issue with action map buttons being unavailable.  (Use enableAutoNavigation(False).)
- Optimize and improve heading sort calculations.
- Correct keyRename() for directories.
- Update the headings when the sort orders are changed.
- Expand the capabilities of the text editor:
  - Sequence the code methods alphabetically.
  - Rename the "updateLine()" method to "updateStatus()" to better reflect what the method does.
  - Add command to duplicate the current line.
  - Add a command to delete all empty and white space only lines.
  - Add a command to remove all duplicated lines in the file.
  - Add a command menu to sort all the lines in the file.  The options are to sort the lines in ascending and descending order.

[keymap.xml] Add new button options to change panels

### CODE REVIEW

**Comment by geeeeeeeeeee** [comment]
> Hi @geeeeeeeeeee, there is a new FileCommander branch from Ian, please test this new version.

I can't find bugs so fast. Looks OK.
One thought, why sortTextMenu on text key? why not long red or long green?
If you really hear me, i prefer a more flexible menu button, to add more functions by the time.

**Comment by jbleyel** [comment]
> > Hi @geeeeeeeeeee, there is a new FileCommander branch from Ian, please test this new version.
> 
> I can't find bugs so fast. Looks OK. One thought, why sortTextMenu on text key? why not long red or long green? If you really hear me, i prefer a more flexible menu button, to add more functions by the time.

Menu button for the action is not correct UX .. then you also need to add all other functions to the context menu and this is a lot of work. That's why we use txt.

**Comment by geeeeeeeeeee** [comment]
> One thought, why sortTextMenu on text-key? why not longRed or longGreen?

longRed stay unused. In the main screen with the file panels there is sort on longRed or longGreen.
OK, i said it, I can't do more.

**Comment by jbleyel** [comment]
> > One thought, why sortTextMenu on text-key? why not longRed or longGreen?
> 
> longRed stay unused. In the main screen with the file panels there is sort on longRed and/or longGreen. OK, i said it, I can't do more.

So .. you wanna redLong as the replacement for "text"?

**Comment by geeeeeeeeeee** [comment]
I told my favorite, but this is one thought that we can merge.

**Pull request merged**
