### PR TITLE
File commander updates

### PR DESCRIPTION
**Pull request by geeeeeeeeeee**
Please merge and if you don't like to say what's wrong on
> Change the sort to size and try your code, that's the reason why we don't add the selection change.

you can than remove the FileCommanderUpdates branch.
My last word.
Thank you and a nice new year

### CODE REVIEW

**Comment by geeeeeeeeeee** [comment]
Mergeable commit for FileCommanderUpdates
https://github.com/geeeeeeeeeee/enigma2/commit/8aab769f5fad5bd3fbf2eb89d1b42e8d8b06e0ed

**Comment by jbleyel** [comment]
We will refactor multi select completely.

**Comment by geeeeeeeeeee** [comment]
New issue:
Multiselect do not show a list of files and directories that will deleted.
Only "Delete the selected directories/files?" is shown.

**Comment by jbleyel** [comment]
Sorry, but this is not helpful.
Please provide step by step how to reproduce the issue.
But this sounds not like an issue.
This is a feature request.

**Comment by geeeeeeeeeee** [comment]
Move and Copy does have this "feature".

**Comment by geeeeeeeeeee** [comment]
...
Select files and process delete on multiselect.
...
What will happen?

**Comment by jbleyel** [comment]
I need to have a deeper look, we may have done this by purpose.

**Comment by geeeeeeeeeee** [comment]
Yes maybe, move and copy check for existing files that will be overwritten.
If multiselect later will work, we don't need that's true.

**Pull request closed without merging**
