### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ejalal**
Add crontab and enigmalight.conf files to backup

### CODE REVIEW

**Comment by ejalal** [comment]
Sorry there's a missing comma at the end of the line

**Comment by atvcaptain** [comment]
please clean pull request and not unnecessary commits

**Comment by ejalal** [comment]
Sorry don't know how to create a merge request only for the files I modifies, most of the commits are merge commits from your master into my working branch.
Will try to fix that now

**Comment by atvcaptain** [comment]
simple first merge last atv changes to your fork, or clean fork all new and make your change and than send pull request and not from old fork revision

i add you r changes now, you dont must send again

**Pull request closed without merging**
