### PR TITLE
revert encoding remapping and huffman string convert logic.

### PR DESCRIPTION
**Pull request by nx111**

### CODE REVIEW

**Comment by atvcaptain** [comment]
have you fix the issue user have report ?

**Comment by nx111** [comment]
they report that encoded by huffman? if that, may be fixed.

**Comment by atvcaptain** [comment]
we get no feedback from you , have you see this: https://github.com/openatv/enigma2/pull/1043
so we have frist revert all, many user report issue after the big changes, so we must test first more before we can add again

**Comment by nx111** [comment]
I rebase the patches, you can merge after tested it.

**Pull request closed without merging**
