### PR TITLE
Update About.py

### PR DESCRIPTION
**Pull request by badsystem**

### CODE REVIEW

**Comment by jbleyel** [comment]
Why?
* do we really need to translate GHz
* If yes then please  _("%s GHz")

**Comment by badsystem** [comment]
- in other places of the image these units have a translation
- _ ("% s GHz") is not translated to About

**Comment by jbleyel** [comment]
_("%s GHz") is ok 
_("1.0 GHz") is not ok

**Comment by badsystem** [comment]
for the Zgemma H9 Combo the CPU frequency is displayed 
```
	elif getMachineBuild() in ('dagsmv200', 'gbmv200', 'u51', 'u52', 'u53', 'u532', 'u533', 'u54', 'u55', 'u56', 'u57', 'u571', 'u5', 'u5pvr', 'h9', 'i55se', 'h9se', 'h9combose', '**h9combo**', 'h10', 'h11', 'cc1', 'sf8008', 'sf8008m', 'sf8008opt', 'hd60', 'hd61', 'pulse4k', 'pulse4kmini', 'i55plus', 'ustym4kpro', 'beyonwizv2', 'viper4k', 'multibox', 'multiboxse'):
		return "**1,6 GHz**"
```
this value "1,6 GHz" is not translated

**Comment by jbleyel** [comment]
please check this -> 
https://github.com/openatv/enigma2/commit/eca941c529f8fd5f0be9f9c45a43c695763fb8fb

**Comment by badsystem** [comment]
Everything is OK

**Pull request closed without merging**
