### PR TITLE
Clean up all translations

### PR DESCRIPTION
**Pull request by wedebe**
Clean up all translations

!* NOTE *! This is a prequel to #1787 
Please let me know whether it's easier to review separately or as the
combined (cleanup-all-translations) PR.
* See note below re large number of line changes

This change:
- resets msgstr of unchanged translations to "" for future ease
  of original text changes
- adds references/occurrences of translations in source code
  *(note that this adds a line per msgid (~6,600) per translation (43)
- normalises all translations for consistency of msgid entries
  across all po files
- provides a script to do all of the above

Not part of this change:
- removal of non-found msgid entries (these may be from ext plugins)
- fuzzy fixing
- checking %s/%d count matching in msgid & msgstr

Pre-normalise:

|File|Entries|(Fuzzy)|Unchanged|Translated|Ratio|-|
|---|---|---|---|---|---|---
|ar.po|5705|935|4827|878|13%|-|
|bg.po|5646|971|1510|4136|62%|-|
|ca.po|5865|761|5421|444|6%|-|
|cs.po|5160|1474|1581|3579|54%|-|
|da.po|6665|18|1035|5630|84%|-|
|de.po|6676|0|1295|5381|80%|-|
|el.po|6608|0|590|6018|91%|-|
|en.po|6458|187|3632|2826|42%|-|
|en_GB.po|6734|11|6642|92|1%|-|
|enigma2.pot|6683|0|6683|0|0%|-|
|es.po|5490|1127|1516|3974|60%|-|
|et.po|6340|266|975|5365|81%|-|
|fa.po|5567|1079|4544|1023|15%|-|
|fi.po|5659|958|2023|3636|55%|-|
|fr.po|5678|938|1491|4187|63%|-|
|fy.po|5754|890|5079|675|10%|-|
|he.po|5703|935|5193|510|7%|-|
|hr.po|5860|770|5396|464|7%|-|
|hu.po|6655|0|828|5827|87%|-|
|id.po|5805|810|5291|514|7%|-|
|is.po|5649|1001|4642|1007|15%|-|
|it.po|6377|228|1113|5264|79%|-|
|ku.po|5158|1538|5001|157|2%|-|
|lt.po|6683|690|497|6186|92%|-|
|lv.po|5730|914|4977|753|11%|-|
|nb.po|6605|0|6605|0|0%|-|
|nl.po|6683|0|1088|5595|83%|-|
|no.po|5611|1005|3025|2586|39%|-|
|pl.po|6676|10|1030|5646|84%|-|
|pt.po|5543|1101|3488|2055|31%|-|
|pt_BR.po|5091|1609|3472|1619|24%|-|
|ro.po|5748|891|4995|753|11%|-|
|ru.po|5777|838|966|4811|72%|-|
|sk.po|6605|0|732|5873|88%|-|
|sl.po|5517|1134|4386|1131|17%|-|
|sr.po|5653|997|4675|978|14%|-|
|sv.po|5482|1181|2848|2634|39%|-|
|th.po|5686|961|4839|847|12%|-|
|tr.po|6360|253|957|5403|81%|-|
|uk.po|6650|0|468|6182|92%|-|
|vi.po|6357|248|909|5448|82%|-|
|zh_CN.po|5584|1034|1401|4183|63%|-|
|zh_HK.po|4699|1946|3595|1104|16%|-|

### CODE REVIEW

**Comment by wedebe** [comment]
Upcoming update in progress.

**Comment by Makumbo** [comment]
How can i change the de.po File now? GitHub says "Its too long".
Because i found some minor things:
Line 1842: msgstr "0,2s" (German has Comma instead of Point)
Line 2247: There is a ", 8x" missing" so the Line could be just msgstr ""
Line 12135 could be msgstr "LAN lang"
The definition of Line 23265 (and others) is missing; should'n it be like "#: /lib/python/Plugins/SystemPlugins/IceTV/plugin.py:0 /lib/python/Components/Converter/genre.py:0"

Gruß - Makumbo

**Comment by wedebe** [comment]
Hi @Makumbo, I think our changes overlapped between the time my PR was submitted to when it was merged. If you retry with a fresh branch off 6.4, you'll still find 0.2s; the 8x will indeed fall back using an empty msgstr, and LAN long is now LAN button hold.

Regarding the file reference ; separation, I'll fix that as part of the merge conflict for the 'continued' branch, the .mo compiled but I couldn't find a similar usage in the e2 repo to follow, thanks for the tip!

**Comment by hd75hd** [comment]
@wedebe 

https://github.com/openatv/enigma2/commit/8c55d6916f7142c43ed1eaa8c19d246321866df5#commitcomment-41445871

**Pull request merged**
