### PR TITLE
[InfoBarGenerics]

### PR DESCRIPTION
**Pull request by jbleyel**
[InfoBarGenerics]
* show subservice channels and indicator also if no epg data available

This needs to be finalized by adding of an additional setting.

### CODE REVIEW

**Comment by jbleyel** [comment]
Hi @jeepcook , can you please test this new version.
Please note !!
You need all 3 files.

https://github.com/openatv/enigma2/pull/3004/files

**Comment by jeepcook** [comment]
Hi @jbleyel ,

Installation done.

First tests:
- By default "If EPG available", OK only channels with EPG are listed, icon on
- Always, OK, channels with or without EPG are listed, icon on
- Off, KO, the icon is off but the green button selection is active and we are in the default case ("If EPG available").

Note that I have no specific configuration for green button:
config.misc.ButtonSetup.f1=Module/Screens.ServiceInfo/ServiceInfo
config.misc.ButtonSetup.red=Module/Screens.PluginBrowser/PluginBrowser

**Comment by jeepcook** [comment]
Hi @jbleyel ,

Another case not due to these mod, but the allowed url length seems to be different in .tv bouquet and in groupedservices

An example with a very long Pluto TV url for Pluto TV Action channel which work on .tv bouquet but not as subservice:
http://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/5f8ed1ff5c39700007e2204a/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=%7BTARGETOPT%7D&deviceId=%7BPSID%7D&advertisingId=%7BPSID%7D&us_privacy=1YNY&samsung_app_domain=%7BAPP_DOMAIN%7D&samsung_app_name=%7BAPP_NAME%7D&profileLimit=&profileFloor=&embedPartner=samsung-tvplus

It's just an example to give you the problem. I know this url is not really made for an enigma2 box.

**Comment by jbleyel** [comment]
Please send me your files again via mail with the Pluto in.

**Comment by jeepcook** [comment]
sent done

**Comment by jeepcook** [comment]
A feedback after few days of use. Everything is ok. No problem encountered.
Just a thing which was already in the old version, the history zap is cleaned after zapping to a subservice channel.

**Pull request merged**
