### PR TITLE
Greek translation update 6/7/2016

### PR DESCRIPTION
**Pull request by MCelliotG**
Full Greek translation update in sync with enigma2.pot and de.po

### CODE REVIEW

**Comment by atvcaptain** [comment]
cant merge not in sync !

**Comment by MCelliotG** [comment]
Let me check it and I'll try again. Perhaps because the de.po file contains about 1000 strings that are not included in the enigma2.pot! Shouldn't these strings be available as an addition for all other languages as well?

**Comment by atvcaptain** [comment]
we must create new pot file , but i have less time for this, we planing in the feature a better solution platform for translation, but need time, the german po file is complete other po files some parts missing

**Comment by MCelliotG** [comment]
I can take care of creating a new pot if you like me to.

**Pull request closed without merging**
