### PR TITLE
[ButtonSetup]

### PR DESCRIPTION
**Pull request by jbleyel**
* allow plugin to assign to hotkey only

#2648

### CODE REVIEW

**Comment by geeeeeeeeeee** [comment]
I like it.
1st test perfect.

**Comment by jbleyel** [comment]
I have thought about this and the conclusion is: 
This change is very concerning as you are not able to easily remove the plugin as it is not listed.

**Comment by geeeeeeeeeee** [comment]
You mean disable? not remove!
The way to disable is to remove!

**Comment by jbleyel** [comment]
There was a misunderstanding.

**Pull request merged**
