### PR TITLE
New labels from enigma2.pot. Translation updated.

### PR DESCRIPTION
**Pull request by yeyo**

### CODE REVIEW

**Comment by atvcaptain** [comment]
you have see you change pl.po not enigma2.pot !

**Comment by yeyo** [comment]
Indeed, I've edited pl.po with Poedit and then update missing labels from Poedit update menu. enigma2.pot is not affected.

**Comment by atvcaptain** [comment]
but your change have conflicts cant merge you must resolved this first

**Comment by yeyo** [comment]
Ok, i have to abort this request and pull two, one by one. Sorry for mistake.

**Pull request closed without merging**
