### PR TITLE
[FileCommander] fix and some code changes

### PR DESCRIPTION
**Pull request by geeeeeeeeeee**
Please reopen FileCommanderUpdates

[I have this in queue... you can have a look at it](https://github.com/geeeeeeeeeee/enigma2/tree/geeeeeeeeeee-traditional-key-assignment)

### CODE REVIEW

**Comment by jbleyel** [comment]
> Please reopen FileCommanderUpdates
> 
> [I have this in queue... you can have a look at it](https://github.com/geeeeeeeeeee/enigma2/tree/geeeeeeeeeee-traditional-key-assignment)

This is totally wrong.

**Comment by geeeeeeeeeee** [comment]
Die NavigationActions sollte man doch nicht "mapto", deswegen nehmen wir die FileCommanderActions, weil sie so auch schon passen. Ich hab da echt keine Erfahrung...

**Comment by jbleyel** [comment]
> Die NavigationActions sollte man doch nicht "mapto", deswegen nehmen wir die FileCommanderActions, weil sie so auch schon passen. Ich hab da echt keine Erfahrung...

What’s wrong in the current action map.

**Comment by IanSav** [comment]
As I am the primary developer of this code can all conversations please be in English.

Can I please have more details on what this change is intended to fix?

**Comment by geeeeeeeeeee** [comment]
Sorry for german. I'm used to that only jbleyel is there for me... Hello you!!
Is it OK to use translator, if I don't like do it by myself?
OK, we need the control pad to select a file and this column change is rare, so give us left/right back.

**Comment by IanSav** [comment]
I have worked with @jbleyel to restore LEFT and RIGHT being PAGE UP and PAGE DOWN when there is no other assignment for the LEFT and RIGHT buttons.  This code is implemented inside the action map code and is global across all of openATV Enigma2.  In FileCommander LEFT and RIGHT are used to select the current panel.  This is consistent with the usage of LEFT and RIGHT for panel selection in other screens.  Thus, in this case LEFT and RIGHT will not offer PAGE UP and PAGE DOWN as the specific usage takes precedence.

By the way, what needed fixing in this change?  How do I reproduce the issue that you fixed in this change?

**Comment by geeeeeeeeeee** [comment]
I haven't checkout the new action map code, i'm sad. I need to test later. Thank you.
Please let me ask you: Are you working on FileCommander Multiselct? There are some bugs and i don't like to do twice.

**Comment by IanSav** [comment]
What bugs, no-one has said anything about any bugs?  If they aren't reported then they can't be fixed!

**Comment by geeeeeeeeeee** [comment]
That's great...
https://www.opena.tv/openatv-7-1-py3-10-openssl-3-0-release/61612-file-commander.html
https://www.opena.tv/openatv-7-2-py3-11-openssl-3-07-beta/61269-filecomander-und-multiselect-fehler-7.html

**Comment by IanSav** [comment]
The first thread is a whinge "I don't like it!".  That is not a bug report.  As for, the old version was perfect, I beg to differ.

The other thread is in German so I can't help.

@jbleyel has told me that he will follow the forum threads, that are mostly in German, and he will tell me when there are real bug reports for me to address.  As @jbleyel has not told me of any issues I have not made any more changes.

I am in no way saying that the code is perfect, it was a totally rewrite with little of the original code being retained.  While we strived to have no bugs there are so many ways the code can be used and so many options that issues may arise.  When this code has had more testing and constructive user feedback then I would hope this it can be made more bug free and even better.

If users want issues fixed then they need to confirm that there really is a bug and not just a change to the code.  (The new and improved HELP system will help here.)  Then they need to file appropriate and detailed bug reports.  We need to be clearly told what the issue is, how is it reproduced, what the user expected to happen.   We would also like debug logs so we can try to see what went wrong.  Comments like "it is broken" or "I don't like" it are not appropriate bug reports.

While I am responding let me make a few related observations.
1. I suspect that most users are not using the HELP system to find the commands and options they want.  Some things are being changed to make the *entire* openATV user interface consistent and predictable.  I expect that usage will become easier as more and more of the UI is unified.
2. @jbleyel and I were particularly careful with the FileCommander rewrite to deliver all the features of the old version we could.  I then moved forward and delivered many new and improved features across the code.  I am shocked to read people say that it is less functional than before!
3. The old code was far from perfect and had *many* issues that required attention.  It is disappointing that users do not acknowledge all the time and effort that goes into maintaining the openATV Enigma2 code.
4. I think that some users are stuck in a 15+ year old Enigma2.  They need to consider that Enigma2 needs to change and evolve to suit the times, the available software and the hardware.  For example, the change to Python 3 has forced *MANY* changes to the way Enigma2 works.  Sometimes we are faced with decisions like how can we replace this code that no longer works while trying to keep up with user expectations.  Sometimes the changes can happen without user impact.  Sometimes they force changes to what the user sees.
5. While I mainly work on the UI and usability lately I am also working on code to make Enigma2 easier to maintain.  If we don't make Enigma2 easier to code and maintain then we are going to run out of developers to maintain it.  None of us are paid and we spend significant time on this project I think users should occasionally show a little gratitude for all the good work that we presume that they like rather than all the negative comment.  I understand that users want bugs fixed but sometimes a kind word can keep up our desire to keep going.

**Comment by geeeeeeeeeee** [comment]
https://github.com/geeeeeeeeeee/enigma2/commit/dbf5eae2567bba0efe485f64d1a30a99568dbf38
https://github.com/geeeeeeeeeee/enigma2/commit/43ef0d0bfa3309655d3cc24c6a345d00722abf33
https://github.com/geeeeeeeeeee/enigma2/commit/c256d904cd0d8f6af3c4224fe9800bc57a32d63c
Before you start i have some fixes

**Comment by IanSav** [comment]
There are no bug reports for me to read and review in relation to those changes.
What are the bugs and how do I reproduce them?

**Comment by geeeeeeeeeee** [comment]
i wrote a comment into the commits

**Comment by geeeeeeeeeee** [comment]
can i post https://github.com/openatv/enigma2/pull/2735#issuecomment-1368891869 to the forum?
i'm with you, i like your work but we couldn't use it in the first state.

**Comment by IanSav** [comment]
@jbleyel and I have reviewed your code changes and don't understand what they are trying to fix.  Your comments don't provide any useful information to explain what the problem may be or how to reproduce the problem.  The changes you propose make no sense to us.  For example, why are you removing the "<Parent Directory> from the file list?  Not only does this change make no sense it breaks other things.

If you would like anything fixed in the code please tell us what is wrong and how we can reproduce the issue.

@jbleyel tells me that you are a forum regular.  If you would like to help get the code improved in response to user feedback then I would welcome you translating the user complaints into coherent bug reports that we can process.  Check that what the user is experiencing is really a bug and not a misuse of a changed command.  Suggest that users use the new HELP system to help them understand the options available to them.  If there is a problem then help the users to clearly define the issue and get the steps on how to reproduce the problem.  Often screen captures with arrows and explanation notes can be very helpful.  Finally it always helps if we can get debug logs, particularly if a crash is involved.  Please get a full debug log and not just the crash log as sometimes an issue is triggered well before the crash and it not captured in the crash log.

**Comment by geeeeeeeeeee** [comment]
**This are fixes:**
https://github.com/geeeeeeeeeee/enigma2/commit/dbf5eae2567bba0efe485f64d1a30a99568dbf38
if you have a multiselect on movie with related files, the cursor moves down 1 line.
but the cursor should be on a line without the related files(next movie).

https://github.com/geeeeeeeeeee/enigma2/commit/43ef0d0bfa3309655d3cc24c6a345d00722abf33
if you have multiselect on, we want hide the parent directory like in the old version.
i know it's dirty.

**This are drafts:**
https://github.com/geeeeeeeeeee/enigma2/commit/f83afdc733c23f997610fd16915a273c78462776
the multiselect don't work, this is a working version.

https://github.com/geeeeeeeeeee/enigma2/commit/f5b0f8990da1b35aabc35f11c3cb3e1018a0158f
We can use this as alternative.
If parent directory is selected and Green and Yellow are hidden we can use Green and Yellow to go left or go right column.

Please try to understand the fixes and merge them to FileCommanderUpdates
These drafts can be used as feedback. This is python and not german...

I'll stop here you can comment to the commits you cant understand.
These commits have more comment then code
Sometimes you commit relative less explained.
Please be fair i'd only like to push fixes.

**Comment by jbleyel** [comment]
You always welcome to make changes if there is an error.
But please provide the reason for your change and describe step by step how to reproduce the error.
If a user has a problem with the UI, they must provide a screenshot with a description of the error.
I am pissed off to the max about the comments in the forum.
We have spent weeks making the code more readable, stable and faster.
We also found and fixed many bugs in the process.

**Comment by geeeeeeeeeee** [comment]
Not a good work... ...day
For me it's fine now but they(forum) stay have problems.

**Pull request merged**
