### PR TITLE
Update ImageBackup.py

### PR DESCRIPTION
**Pull request by badsystem**
Translate

### CODE REVIEW

**Comment by jbleyel** [comment]
The image backup strings are not translated by purpose.

**Comment by badsystem** [comment]
They can be translated by adding the appropriate values ​​to the locale. I have it working. But it's up to you, this is just my suggestion.

**Comment by IanSav** [comment]
With these strings being translated, the log files will now be harder to read for developers/users who don't read the translated strings.  Usually all log files are written in US English.

**Comment by badsystem** [comment]
It's up to you. If there's a change, I'd be grateful.

**Comment by IanSav** [comment]
The changes have been merged.  I am just letting you know why I didn't do the translations when I wrote the code.

I may yet add the log messages into the normal log and there they will be in the usual US English.  ;)

**Comment by badsystem** [comment]
Thanks. 
I'm not interested in logs if there were no failures during the development of the skin.

**Pull request merged**
