### PR TITLE
File commander updates

### PR DESCRIPTION
**Pull request by jbleyel**
* Improve multiselect selection index after choose related files.
* Correct selection index after delete and move.

### CODE REVIEW

**Comment by geeeeeeeeeee** [comment]
Now I see and think this will be better.
[[FileCommander] rename error lose currentIndex](https://github.com/geeeeeeeeeee/enigma2/commit/eb00b7546f1ba05f03ef558ba425b8d6abe7f788)

**Comment by jbleyel** [comment]
Please provide the root cause and the info howto reproduce all the issues what you are intending to fix.

**Comment by IanSav** [comment]
As @jbleyel posted, please document the issue you are trying to fix and provide clear steps that we can follow to reproduce the issue.  Don't try to fix the code and force us to try and guess what you are fixing.

Again, as @jbleyel posted, your multi select positioning code is ill-conceived as it only works in name sort order.  It goes completely wrong if any other sort orders are selected.  I noted these issues when I first wrote the code.  That is why the code is the way it has been written.

When you write your fixes you really need to review how your changes will affect *ALL* the code and not just the feature you want to "fix".  A number of your fixes have caused failures in other areas of the code.

**Comment by geeeeeeeeeee** [comment]
> Please change the sort order to date and test your new multi select index code. And you will see why we don't have implemented this.

Please provide more information about...
This works too but your code doesn't work on name sort order.

**Comment by geeeeeeeeeee** [comment]
I don't want waste your time. I'll stop, to give you peaces of code.
But please don't forget my https://github.com/openatv/enigma2/issues/2649
This was clear to understand.
I'm sorry, I'm not a programmer and I don't know the vocation, that you need to detect a bug.

**Comment by jbleyel** [comment]
> > Please change the sort order to date and test your new multi select index code. And you will see why we don't have implemented this.
> 
> Please provide more information about... This works too but your code doesn't work on name sort order.

Change the sort to date and try your code, that's the reason why we don't add the selection change.

**Comment by jbleyel** [comment]
> I don't want waste your time. I'll stop, to give you pieces of code.
> But please don't forget my #2649
> This was clear to understand.
> I'm sorry, I'm not a programmer and I don't know the vocation, that you need to detect a bug.

We only need a short description how to reproduce the issue.

**Comment by jbleyel** [comment]
What's the exact reason for this -> https://github.com/openatv/enigma2/pull/2738/commits/2d81e48dda7b2dc04e95f06e37a1f831f4aa3836

Can you please provide step by step how to reproduce.

**Comment by geeeeeeeeeee** [comment]
https://github.com/openatv/enigma2/pull/2698 (Co-authored-by: geeeee)
Look for "startIndex"
Now I understand better the Issue and improved the code.
I saw this Issue on a similar code point I missed https://github.com/openatv/enigma2/pull/2698

**Comment by geeeeeeeeeee** [comment]
> > > Please change the sort order to size and test your new multi select index code. And you will see why we don't have implemented this.
> > 
> > 
> > Please provide more information about... This works too but your code doesn't work on name sort order.
> 
> Change the sort to size and try your code, that's the reason why we don't add the selection change.

Please provide more information about...
This works too but your code doesn't work on name sort order.

**Comment by jbleyel** [comment]
There will be a new PR for you to test.
This change should cover all the issues.

**Pull request closed without merging**
