### PR TITLE
Expanding the functionality of the PiP

### PR DESCRIPTION
**Pull request by alec-cs**
Hi Captain,

I have expanded and modified the existing PiP solution for Enigma2.

There are 3 ways:
  - standard -> Functions that are currently running
  - noadspip -> Ads could be filtered out while ads go, another channel could be watched
  - side-by-side -> If you want to watch multiple shows at once, you could use this mode the right way

The PiP mode switching window makes it easy to change the mode (PiP button long). No need to click multiple menu items in the main settings.

noadsPiP mode - Solution steps (hopefully better understood):
1.) I see live TV broadcast on the TV screen.
2.) When I see an advertisement (ad) on the screen, I press a button on the remote control (PiP button or a programmed button).
3.) The active channel will be placed (moved) in the PiP window (with the ad)
4.) The following channel will be displayed on the main screen (Channel after the active channel).
5.) I see: Main screen (no ads) + PiP screen (with ads)
6.) When I see the ad end in the PiP window, I press a button on the remote control again (PiP button or programmed button).
7.) The contents of the PiP window will be displayed (moved) on the main screen and the PiP window will disappear.

The advertisement (ad) is viewed by sight, operation would be manual without automation!
I think this is a useful feature!

side-by-side mode - Solution steps (hopefully better understood):
1.) After pressing the PiP (or programmed) button, the current channel will be displayed on the left side of the screen and the channel following the current channel on the right.
2.) The live broadcast on the left would be active (sound here), the live broadcast on the right would be inactive.
3.) You can change the Active status character by pressing the LEFT  ( < ) button on the remote control, left and right live broadcasts can be swapped. 
All operations affect only the active channel, left screen (channel change, EPG operations, ...).
4.) Press the RIGHT button (>) to change the right screen with the Channel selection +/- buttons (Change inactive screen channel).
5.) Pressing the EXIT button will only activate the live broadcast on the main screen, the inactive live broadcast will disappear from the screen.
When you press the PiP (or programmed) button, the only inactive live broadcast will be on the main screen.

Other EPG and channel switching functions are working well, I have solved other problems.

My solution works fine on my system (openATV 6.2)!
Usable and functional!

Unfortunately, I haven't tried it on openATV 6.4. Sorry.
If something else is wrong, I'll fix it.

Functions that do not work well in the base system:
- A feature is not working properly in PiP (regardless of my development).
If I press "UP" or "DOWN" on the remote control, this function will disable PiP!
Why? Please look at it!
- The "LEFT" ( < ) and "RIGHT" ( > ) buttons operate the side-by-side PiP mode. Unfortunately, in this case, the basic EPG info does not work.
Why? Please look at it!

I hope you understand what I mean. If you need me I'll send you a photo of that feature!

Check out my solution and if it works well then merge it.
If you have any questions please do not hesitate to contact me!

Regards:
Alec

### CODE REVIEW

**Comment by atvcaptain** [comment]
test here with atv 6.4  noadsPiP mode works as you say all fine
but side-by-side mode show issue
after press pip enable key this enable pip but with a small pip windows on upper right corner
and when press right key i see a black bar on screen channel swizcj in the pip windows works,
left key works too

**Comment by atvcaptain** [comment]
oh see issue with left right keys when pip disabled not working any more

**Comment by alec-cs** [comment]
Hi,
I will continue the changes, it will take some more time...

I will also solve it, if there is no PiP button on the remote control, it will still work with the usual "blue" button.   I'll post the modified files soon.

I know the LEFT and RIGHT button problem, but I don't know the solution yet.
I will ask for some help and information in this!  I don't really understand this "keymap" usage.

What do you think would be the solution to make the "LEFT, RIGHT" button work well?

**Comment by alec-cs** [comment]
Hi Captain,

I was done with my development.

I wanted to bring the source code up to date before uploading my own program codes.
This error has occurred!
What's the problem? What do I do now?

I should close the "Pull requests" and try the "pull" again?
Or Fork again?

I look forward to your reply.

**Comment by atvcaptain** [comment]
update your local branch and send new pull request

**Pull request closed without merging**
