### PR TITLE
[EPGList] Add optional channel numbers to Graphical EPG,

### PR DESCRIPTION
**Pull request by AbuBaniaz**
thanks to @darkdreamingdan for original code.

Please check these commits before merging.
https://github.com/darkdreamingdan/enigma2/commit/cc70328a80d659e00124d34c954a45db2b9d0474
https://github.com/OpenViX/enigma2/commit/43d221fcc073ae5bfe4187b10b72c239e3e33edb

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Some subsequent commits missing. Crashes reported on OpenVix. 
May try again later

**Comment by davesayers2014** [comment]
Is there an update to this

**Comment by darkdreamingdan** [comment]
It would simply require a pull request including subsequent commits

**Comment by davesayers2014** [comment]
thanks ive got as far as var-line nubers right but I can not get the options working

**Comment by AbuBaniaz** [comment]
I'll leave it to you

**Pull request closed without merging**
