### PR TITLE
text bug in SoftwareManager/ImageBackup.py 

### PR DESCRIPTION
**Pull request by atom89**
When an image backup is made, this line is seen in the output on the screen:
"Back-up Tool for a BRAND MODEL".
for some brand names it should be like this:
"Back-up Tool for an BRAND MODEL".
if the brand name starts with: a, e, i, o, u, (and some exeptions like the X in Xtrend) then it should be 'an' instead of 'a'

i have replaced line 255:

self.message += (_("Back-up Tool for a %s\n" %self.SHOWNAME)).upper() 

with this:

if getMachineBrand().startswith('A') or getMachineBrand().startswith('E') or getMachineBrand().startswith('I') or getMachineBrand().startswith('O') or getMachineBrand().startswith('U') or getMachineBrand().startswith('Xt'):
    self.message += (_('Back-up Tool for an %s\n') % self.SHOWNAME).upper()
else:
    self.message += (_('Back-up Tool for a %s\n') % self.SHOWNAME).upper()

i also made a little change with the tanslatable part.
i changed this:
(("Back-up Tool for a %s\n" %self.SHOWNAME))
into this:
(('Back-up Tool for a %s\n') % self.SHOWNAME)

this makes it easier to tanslate.
in the old way there should be a translation for every BRAND and MODEL.

now it looks ok.

[ImageBackup.zip](https://github.com/openatv/enigma2/files/2074045/ImageBackup.zip)

### CODE REVIEW

**Comment by atvcaptain** [comment]
sorry we cant merge this, please sync before send pull request

**Comment by atom89** [comment]
i don't know what you mean with 'sync', or how to do that.
i'm new at this.
i will look it up on github info, and try again.

**Comment by arn354** [comment]
The problem is that your pull-request contains too many changes to identify the real change, because it seems your repository was outdated once you applied your changes. You should always first update your cloned openatv enigma2 repository before you change, commit and create a pull-request for something.

1.) copy your modified files aside
2.) delete the openatv enigma2 repository on your github account
3.) clone the openatv enigma2 repository again
4.) re-apply your changes and create a pull-request
5.) your pull-request will only show the changes you applied

**Comment by atom89** [comment]
Thank you for your help. i think i did everything wright, but creating a pull-request doesn't work.
i made some screenshots of my actions.
when i select Branch/Create pull request/Create without pushing , i get the webpage for creating a pull request, but the button on the screen doesn't work.
can you tell me what i'm doing wrong ?

**Comment by atom89** [comment]
Here is a recent file with the fix.

[ImageBackup.zip](https://github.com/openatv/enigma2/files/2544343/ImageBackup.zip)

it was comitted to OpenEight yesterday.

https://github.com/Openeight/enigma2/commit/ccc13281e76259383b7d8209cb4c6ab7c7080efe

**Comment by atvcaptain** [comment]
https://github.com/openatv/enigma2/commit/a720c98313720d05795fae9a7bbf43dd6df651e2

**Pull request closed without merging**
