### PR TITLE
Update hu.po

### PR DESCRIPTION
**Pull request by alec-cs**
v2.5

### CODE REVIEW

**Comment by alec-cs** [comment]
Update enigma2.pot and Update [ChannelSelection.py] make hour_min function

**Comment by madieatv** [comment]
enigma2.pot has a conflict.

**Comment by alec-cs** [comment]
Hi

I created the hour_min function in ChannelSelection.py, so I had to modify the enigma2.pot file.

I just added the following lines to the enigma2.pot file:

+msgid "%02d.%02d - %02d.%02d (%s %s)"
+msgstr ""
+
+msgid "time_hour"
+msgstr "hour"
+
+msgid "time_min"
+msgstr "min"

Discard the file or resolve conflicts.

- - - - -

Please solve the following: hour_min (83) -> '1 hour 23 min'

**Comment by alec-cs** [comment]
Hi,

No conflict!

**Pull request merged**
