### PR TITLE
Tweak record error message

### PR DESCRIPTION
**Pull request by wedebe**
#2995

### CODE REVIEW

**Comment by jbleyel** [comment]
We have defined that warnings and errors should be end with "!" and not "."

**Comment by jbleyel** [comment]
This is ok to me:

`
message = _("Write error at start of recording: %s\n%s") % ((_("The device was not found!"), _("The device is not writable!"), _("The device is full!"))[self.mountPathErrorNumber - 1], self.name)
`

`AddPopup(text=_("Write error while recording: %s") % (_("An unknown error occurred!"), _("The device was not found!"), _("The device is not writable!"), _("The device is full!"))[err], type=MessageBox.TYPE_ERROR, timeout=0, id="DiskFullMessage")
`

**Comment by wedebe** [comment]
> We have defined that warnings and errors should be end with "!" and not "."

Can you point me to where this (and other formatting/style decisions) are documented so I can save time on future suggestions, please?

**Comment by jbleyel** [comment]
> > We have defined that warnings and errors should be end with "!" and not "."
> 
> Can you point me to where this (and other formatting/style decisions) are documented so I can save time on future suggestions, please?

Not finished.
Should be placed here.

https://github.com/openatv/enigma2/tree/master/doc

**Comment by wedebe** [comment]
Sonarfailuree:

```
INFO: Analysis report compressed in 580ms, zip size=771 KB
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 9:05.482s
INFO: Final Memory: 64M/220M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
ERROR: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
Error: Process completed with exit code 2.
```

**Comment by jbleyel** [comment]
Configure SONAR for remote branches is not that easy.

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/68191fbb852684bab28afdf2d736373df6c87824

**Pull request closed without merging**
