### PR TITLE
[vuplus] support focus animation for listbox

### PR DESCRIPTION
**Pull request by thawtes**
Support focus animation for listbox

Based on
http://code.vuplus.com/gitweb/?p=vuplus_dvbapp;a=commitdiff;h=74f5884fdc5a23465cf40c27b5c069ff7d882746

### CODE REVIEW

**Comment by atvcaptain** [comment]
| python/enigma_python.cpp: In function 'PyObject* _wrap_setAnimation_current_listbox(PyObject*, PyObject*)':
| python/enigma_python.cpp:58196:3: error: 'setAnimation_current_listbox' was not declared in this scope
|    setAnimation_current_listbox(arg1);
|    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
| python/enigma_python.cpp:58196:3: note: suggested alternative: '_wrap_setAnimation_current_listbox'
|    setAnimation_current_listbox(arg1);
|    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
|    _wrap_setAnimation_current_listbox
| Makefile:2294: recipe for target 'python/enigma_python.o' failed


all gigablue build now broken

**Comment by thawtes** [comment]
i have no idea about gigablue
revert this commits if there are problems

**Comment by atvcaptain** [comment]
i have fix it

**Comment by thawtes** [comment]
thank you dear @atvcaptain

**Pull request merged**
