### PR TITLE
Updated the PO Translation files. 

### PR DESCRIPTION
**Pull request by neoatomic**
I noted that many of the PO files where not up-to-date and didn't contain the latest entry's from the POT file. So i ran them all trough Poedit.

* Added the latest entry's from the POT file.
* Validated all files with Poedit, so they should be error free.
* Poedit made the PO's a little more uniform.
* Changed the Project IDs to `OpenATV`.
* The `ku` Kurdish file was set to `en` (English) fixed that also.
* Some small fixes/updates.

There are a few PO Language files that don't have the recommended `Plural-Forms` setting according to Poedit. i'm not sure why that is, so i didn't touch/change them. But those are `AR/CS/FR/HR/LV/RO/SL/TH/TR/`

As this is a large PR, please test/review.

### CODE REVIEW

**Comment by neoatomic** [comment]
Yeah, this is the second time that a 1 character PR seems to be more important than this substantiation one and there for coursing merge conflicts. I'm not going to re-base this PR again...

**Comment by neoatomic** [comment]
@atvcaptain You might also want to check [crowdin.com](https://crowdin.com/). They offer free open source project accounts to help managing the translations (PO files). We are using that for our [own](https://crowdin.com/project/sickrage) project, and its way easier to maintain the PO's.

And probbebly will boost (code)contributions from users as they will have a quick/easy way to help translating.

**Comment by atvcaptain** [comment]
ah nice never see this, i have open a sample test : https://crowdin.com/project/openatv
and send a info to crowdin.com lets see, then we are approved we make a new clean pot and start thx for help

**Comment by neoatomic** [comment]
@atvcaptain Was the (open source) account approved.? And do you plan to use crowdin in the future for translations.? (If that is the case could you merge the Git-hub NL.po to Crowdin.? The git-hub nl.po is at 88% complete the Crowdin is at 62%.)

**Comment by atvcaptain** [comment]
hi yes openatv was now approved, but for start we must create frist a new pot file and merge all po files again, but i am the next days busy , have less time to add this

**Comment by neoatomic** [comment]
No problem, just let me know if and when you are ready to accept new translations. :+1:

**Pull request closed without merging**
