### PR TITLE
Update network test addresses

### PR DESCRIPTION
**Pull request by wedebe**
Update network test addresses (see #1791 )

This change updates urls and ip addresses used in network tests for more high-availability, international/local resolution

### CODE REVIEW

**Comment by Schimmelreiter** [comment]
Please don't introduce or re-introduce 1990s logic.
The first block turns the check into an IPv4-only check:

```
root@solo2se ~ # ping -c 1 www.google.com
PING www.google.com (2a00:1450:4005:800::2004): 56 data bytes
64 bytes from 2a00:1450:4005:800::2004: seq=0 ttl=119 time=44.448 ms

--- www.google.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 44.448/44.448/44.448 ms
root@solo2se ~ # ping -c 1 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
ping: sendto: Network is unreachable
root@solo2se ~ #
```

**Comment by wedebe** [comment]
@Schimmelreiter , can you suggest what I should change it to and I'll make the change.I haven't changed any logic, merely the pre-existing addresses.

**Comment by Schimmelreiter** [comment]
You could add cmd4 to cmd6 (And the calls to them) with the literal IPv6 counterparts for the literal IPv4 checks:

For 1.1.1.1 the IPv6 counterparts are
2606:4700:4700::1111
2606:4700:4700::1001

For 8.8.8.8 the IPv6 counterparts are
2001:4860:4860::8888
2001:4860:4860::8844

and for OpenDNS the IPv6 addresses are
2620:119:35::35
2620:119:53::53

**Comment by wedebe** [comment]
I'm not experienced in Python networking so wanted to make the least amount of change for at least some benefit. I'll resubmit the PR with the second block change only and link to this issue to allow someone with the right experience to implement the IPv6 change if that's ok?

**Pull request closed without merging**
