### PR TITLE
Add optional channel numbers on epg 

### PR DESCRIPTION
**Pull request by davesayers2014**
Add guidebouquetlist for supported skins (epgtabs)

### CODE REVIEW

**Comment by arn354** [comment]
```
17:38:16.784 Traceback (most recent call last):
17:38:16.784   File "/usr/lib/enigma2/python/mytest.py", line 26, in <module>
17:38:16.785     from Screens import InfoBar
17:38:16.785   File "/usr/lib/enigma2/python/Screens/InfoBar.py", line 4, in <module>
17:38:16.785   File "/usr/lib/enigma2/python/Screens/MovieSelection.py", line 342, in <module>
17:38:16.785   File "/usr/lib/enigma2/python/Screens/ParentalControlSetup.py", line 10, in <module>
17:38:16.786   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 21, in <module>
17:38:16.786   File "/usr/lib/enigma2/python/Screens/EpgSelection.py", line 1777
17:38:16.786     self.skinName = 'EPGSelection'
17:38:16.787                                  ^
17:38:16.787 IndentationError: unindent does not match any outer indentation level

```
i'll merge and fix

**Comment by davesayers2014** [comment]
Sorry I'm not sure how that happened thanks for fixing it

**Comment by arn354** [comment]
Sorry hat to revert, as there were issues with config.epgselection.overjump set to yes for example.

here is the git-diff to reinstate everything - i am unfortunatly not able to fix that quickly.

[add-channelnumber-to-epg.txt](https://github.com/openatv/enigma2/files/531963/add-channelnumber-to-epg.txt)

**Comment by davesayers2014** [comment]
Is there any chance of someone looking at this I cant find the issues to rectify the bug plus there has been more commits to the default py files. Even if epgselection.py isn't used because there's plenty of other versions that work but it would be great to add optional channel numbers on epg.

**Comment by arn354** [comment]
config.epgselection.overjump set to yes
then the crash occurs
could you provide a cleaned up pull-request? Only for channelnumbers?

**Comment by davesayers2014** [comment]
Ok I think ive managed to include all the latest commits pull request here https://github.com/openatv/enigma2/pull/546

**Pull request merged**
