### PR TITLE
Movistar+ 7 days EPG

### PR DESCRIPTION
**Pull request by pizzelnet**
Cannot check, sorry.

### CODE REVIEW

**Comment by atvcaptain** [comment]
without check we cant merge sorry

**Comment by pizzelnet** [comment]
Hi! Could you please check it for me? or at least help me to integrate the 7 days movistar+ EPG. It would be a great feature especially for Spanish users of OpenATV images, since many other images such as OpenLD or OpenSPA have already implemented these changes.
I have checked the changes regarding the previous modifications I made and I think it's all OK as I have also compared them with those of the images mentioned above.
The files included in the attached zip file should be placed at /etc in order to have the EPG in HD channels.
I hope you help us!
Thanks and regards from Spain.
[mhw.zip](https://github.com/openatv/enigma2/files/182915/mhw.zip)

**Comment by atvcaptain** [comment]
last merge have break all, need some time i must check this offline

**Comment by pizzelnet** [comment]
Ok, thanks a lot. I really appreciate it!

**Pull request closed without merging**
