### PR TITLE
update polish translations

### PR DESCRIPTION
**Pull request by drakulis**

### CODE REVIEW

**Comment by jbleyel** [comment]
Please contact the other polish translators and use weblate for the next time.
Thanks

**Comment by drakulis** [comment]
@jbleyel Ok, will use weblate next time. But I don't know what should I now. So I have couple of questions since I'm using Weblate for the first time:
1. As I see my changes are not available in weblate (yet?). Does it mean they will be overwritten when you synchronize weblate with github?
2. Shall I redo my translations in weblate now?
3. Is there any approval process for the translations? If yes, who is doing it?
4. Is there any group (github/weblate) of polish translators I can contact?

**Comment by jbleyel** [comment]
The zip file here is the latest po from weblate and I don't have overwrite your last changes with this file.
You will find the other translators in the zip.
You can contact the other translators in weblate using comments.
There is no approval process.
I do normally get the latest version from weblate and push the changes to the main repro.

**Comment by jbleyel** [comment]
If you have finished on weblate please give me a sign.

**Comment by drakulis** [comment]
@jbleyel I've made lots of adjustments in polish translation on weblate. 
Shall I notify you anytime I do anything on weblate? Or you are fetching all weblate translations automatically from time to time?

**Comment by drakulis** [comment]
I've moved all my changes to weblate, so  weblate is now my source of truth. If you have conflicts during merge weblate to github you can just overwrite the changes which I've made throught github pull requests

**Comment by drakulis** [comment]
@jbleyel sorry, that I'm contacting you via comment i closed PR but I don't know how to do it different way. I can't find any contact form in Weblate.

I just want to mention that I've pushed next batch of polish translations on Weblate. Would be great if you could merge and release it.

**Pull request merged**
