### PR TITLE
py3 compatible

### PR DESCRIPTION
**Pull request by persianpros**
@jbleyel 

We use this in OV as py2/py3 compatible, is it ok with 6.5 which is for py3 only?

### CODE REVIEW

**Comment by jbleyel** [comment]
6.5 ist NOT py3 only!!

**Comment by jbleyel** [comment]
This needs to be testet first for py2 and py3

**Comment by persianpros** [comment]
Then it should be fine as we're using for py2 for now.

**Comment by jbleyel** [comment]
has_key and isinstance should be no difference.
I'm not sure about sorted list result for py3.

**Comment by jbleyel** [comment]
Hi @atvcaptain , please check.

**Comment by persianpros** [comment]
@jbleyel 

Should I send the PEP8 for 6.4 branch? As you merge from 6.4 to 6.5 I think it's needed but your call.

**Comment by jbleyel** [comment]
Why not. I have done this for 6.5 already.

**Comment by jbleyel** [comment]
PY3 Docu:

You can also use the list.sort() method. It modifies the list in-place (and returns None to avoid confusion). Usually it’s less convenient than sorted() - but if you don’t need the original list, it’s slightly more efficient.

**Comment by jbleyel** [comment]
Please make a new pull but do only the has_key changes.

**Pull request closed without merging**
