### PR TITLE
Update uk.po

### PR DESCRIPTION
**Pull request by badsystem**

### CODE REVIEW

**Comment by jbleyel** [comment]
we are using weblate only for translation

**Comment by badsystem** [comment]
it is not possible to add a line for translation there

**Comment by jbleyel** [comment]
That’s not working if this line is not in the pot file. Where is this text?

**Comment by badsystem** [comment]
The text itself is in lib/python/Tools/ISO639.py
Outputs to AudioSelect

**Comment by jbleyel** [comment]
The values from ISO639 are not prepared for translation.
That means your change will have no effect.

**Pull request closed without merging**
