### PR TITLE
Remove superfluous usage of skin_default in image paths, don't hardcode these kind of things.

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by persianpros** [comment]
@IanSav should I close this PR? Seems ATV doesn't need it ...

**Comment by arn354** [comment]
we need it i think, but need also look into our default-skin, no one found time yet. If that get merged without looking into default-skin - wrong images will then be shown (same name of image in different folder but different look).

**Comment by IanSav** [comment]
OpenATV has the same new Directories.py so it would be good if the changes are made consistently.

The Metrix skin may also need to be adjusted but it is not configured like a normal skin and will probably require a Metrix expert to work on the update.

**Comment by persianpros** [comment]
@IanSav 

Would you please send your date/time changes to PLi or us as I really like your https://github.com/OpenVisionE2/enigma2-openvision/blob/develop/doc/Enigma2DateTime.pdf and changes.

If it's not possible please point me to the needed commits so I could cherry-pick them all :+1:

**Comment by IanSav** [comment]
@persianpros:  The date/time changes are spread out over very many pull requests.  Some of the code is very easy to copy but some of it is very tedious to duplicate/implement.

I would be happy to help you migrate the changes and help you identify and understand how to modify the other parts of Enigma2 to work with the date/time infrastructure.  Is there somewhere we can chat about the details?

By the way, sorry for the delay in responding.  I misplaced my reminder to respond to your enquiry.

**Comment by persianpros** [comment]
@IanSav if it's possible for you please register at our forum https://forum.openvision.tech or send me a PM in PLi forum.

Thank you very much for your tremendous contribution to enigma2 scene :+1: :100: :1st_place_medal:

**Pull request closed without merging**
