### PR TITLE
[keytranslation]

### PR DESCRIPTION
**Pull request by jbleyel**
* remove usage of keytranslation.xml
* add remapping of keytranslation.xml into rcinput

### CODE REVIEW

**Comment by Darek-sm** [comment]
Why did you do that? For example many TVs like LG OLEDs sends by HDMI CEC KEY_PREVIOUS instead KEY_EXIT. keytranslation.xml was the easiest way to fix it. What is the solution afer change?

**Comment by jbleyel** [comment]
Please provide your keytranslation.xml entries what you use to fix the HDMI CEC issue.

**Comment by Darek-sm** [comment]
`<keymap>
        <translate>
                <device name="dreambox advanced remote control (native)">
                        <key from="KEY_PREVIOUS" to="KEY_EXIT"/>
                </device>
        </translate>
</keymap>`

**Comment by jbleyel** [comment]
This will replace all KEY_PREVIOUS to KEY_EXIT and also effects you remote control.
Do you accept that?

**Comment by Darek-sm** [comment]
Yes, I know and accept that.

**Comment by jbleyel** [comment]
Please create keymap_usermod.xml in /usr/share/enigma2/ with the content of your keytranslation.xml

Then copy the ActionMap.py from this zip to /usr/lib/enigma2/python/Components/

[ActionMap.py.zip](https://github.com/openatv/enigma2/files/15139921/ActionMap.py.zip)

And tell me if this works.

**Comment by jbleyel** [comment]
You only need this xml content:

```
<keymap>
        <translate>
                <device name="dreambox advanced remote control (native)">
                        <key from="KEY_PREVIOUS" to="KEY_EXIT"/>
                </device>
        </translate>
</keymap>
```

**Comment by Darek-sm** [comment]
Yes, now it works perfectly :)

**Comment by jbleyel** [comment]
okay .. is this workaround ok for you?

**Comment by Darek-sm** [comment]
Yes. Do I need to replace that python file on every future update of OpenATV?

**Comment by jbleyel** [comment]
> Yes. Do I need to replace that python file on every future update of OpenATV?

No. I have changed the code.

**Comment by jbleyel** [comment]
There will be another solution for your problem but this is not finished yet.

**Comment by Darek-sm** [comment]
Great. Thank you for your time.

**Comment by jbleyel** [comment]
> Great. Thank you for your time.

No problem.
Your issue is new for me that's why I have removed the keytranslations.xml

**Pull request merged**
