### PR TITLE
Add New Feature Horizontal menu ...

### PR DESCRIPTION
**Pull request by fairbird**
-You can enable new menu under (menu > setup > Usage & GUI > Cusomize > Show Main menu as).
-Should be to add screens of new Horizontal menu in any skin you want to support new menu.
-Important to Add screen to skin.xml to enable/shown new menu .
If skin.xml doesn't have screen or If you add it on other .xml file then Horizontal menu will not work .. Default menu will be work automatically.
-As in this cmmit you can import screens + should be add (icon1.png) in buttons folder.
https://github.com/openatv/MetrixHD/pull/385

### CODE REVIEW

**Comment by iPkay** [comment]
first crash ...

12:12:32.1784 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 8b 1
12:12:32.1833 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-] KEY: 139 0 KEY_MENU MENU
12:12:32.1841 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-] [ActionMap] Keymap 'InfobarMenuActions' -> Action = 'mainMenu'.
12:12:32.1969 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-] [SCREENNAME]  InfoBar
12:12:32.1977 [   ] service/servicedvb.cpp:1747 timeshift [eDVBServicePlay] timeshift
12:12:32.2165 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-] Traceback (most recent call last):
12:12:32.2170 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
12:12:32.2175 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 1646, in mainMenu
12:12:32.2180 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 328, in openWithCallback
12:12:32.2187 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]     dlg = self.open(screen, *arguments, **kwargs)
12:12:32.2191 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 341, in open
12:12:32.2198 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
12:12:32.2202 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 276, in instantiateDialog
12:12:32.2208 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
12:12:32.2211 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 298, in doInstantiateDialog
12:12:32.2217 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]     dlg = screen(self, *arguments, **kwargs)
12:12:32.2221 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]   File "/usr/lib/enigma2/python/Screens/Menu.py", line 1097, in __init__
12:12:32.2235 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]     Menu.__init__(self, *x)
12:12:32.2240 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]   File "/usr/lib/enigma2/python/Screens/Menu.py", line 276, in __init__
12:12:32.2246 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]     self.addMenu(m_list, x)
12:12:32.2250 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]   File "/usr/lib/enigma2/python/Screens/Menu.py", line 149, in addMenu
12:12:32.2255 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]     menupng = MenuEntryPixmap(entryID, self.png_cache, lastMenuID)
12:12:32.2259 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]   File "/usr/lib/enigma2/python/Screens/Menu.py", line 49, in MenuEntryPixmap
12:12:32.2263 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-]     png = LoadPixmap(resolveFilename(SCOPE_CURRENT_SKIN, 'mainmenu/missing.png'), cached=True)
12:12:32.2268 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:12:32+0200 [-] NameError: global name 'LoadPixmap' is not defined
12:12:32.2269 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method HelpableActionMap.action of <Components.ActionMap.HelpableActionMap instance at 0xafbb9fd0>>,('InfobarMenuActions', 'mainMenu')) failed)

-> from Tools.LoadPixmap import LoadPixmap in Menu.py added

next crash ...

12:16:53.8504 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 8b 1
12:16:53.8554 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-] KEY: 139 0 KEY_MENU MENU
12:16:53.8562 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-] [ActionMap] Keymap 'InfobarMenuActions' -> Action = 'mainMenu'.
12:16:53.8669 [   ] gdi/epng.cpp:24 loadPNG [ePNG] couldn't open mainmenu/missing.png
12:16:53.8782 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-] [SCREENNAME]  InfoBar
12:16:53.8998 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-] Traceback (most recent call last):
12:16:53.9003 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
12:16:53.9010 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 1646, in mainMenu
12:16:53.9015 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 328, in openWithCallback
12:16:53.9022 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]     dlg = self.open(screen, *arguments, **kwargs)
12:16:53.9026 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 341, in open
12:16:53.9037 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
12:16:53.9042 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 276, in instantiateDialog
12:16:53.9048 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
12:16:53.9052 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]   File "/usr/lib/enigma2/python/mytest.py", line 298, in doInstantiateDialog
12:16:53.9057 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]     dlg = screen(self, *arguments, **kwargs)
12:16:53.9061 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]   File "/usr/lib/enigma2/python/Screens/Menu.py", line 1098, in __init__
12:16:53.9072 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]     Menu.__init__(self, *x)
12:16:53.9077 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]   File "/usr/lib/enigma2/python/Screens/Menu.py", line 361, in __init__
12:16:53.9082 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]     self.hide_show_entries()
12:16:53.9086 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]   File "/usr/lib/enigma2/python/Screens/Menu.py", line 655, in hide_show_entries
12:16:53.9094 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]     m_list.sort(key=lambda listweight : int(listweight[4]))
12:16:53.9098 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]   File "/usr/lib/enigma2/python/Screens/Menu.py", line 655, in <lambda>
12:16:53.9105 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-]     m_list.sort(key=lambda listweight : int(listweight[4]))
12:16:53.9110 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-10-01 12:16:53+0200 [-] TypeError: int() argument must be a string or a number, not 'NoneType'
12:16:53.9112 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method HelpableActionMap.action of <Components.ActionMap.HelpableActionMap instance at 0xafb9c198>>,('InfobarMenuActions', 'mainMenu')) failed)

please check your commit.

**Comment by fairbird** [comment]
I have test it on my DM920 with latest OpenaTV nd works just fine without Crash ..

**Comment by iPkay** [comment]
OK, I'll test it again tomorrow.

**Comment by fairbird** [comment]
I will Also test today with new openatv image ..
If any error I will try to fix it and push new requests again

**Comment by fairbird** [comment]
Yes there id crash .. I have fix it ..
Now should I make new push requests or you can open this commit to edit it ?!

**Comment by iPkay** [comment]
Please make a new request - i can't this reopen.

**Comment by fairbird** [comment]
Ok .. I will do it now

**Pull request closed without merging**
