### PR TITLE
Add dayname to Date selection

### PR DESCRIPTION
**Pull request by wedebe**
Date/time Input screen doesn't show day name. This fixes that.

### CODE REVIEW

**Comment by wedebe** [comment]
This change hasn't made it into 2023-10-16

Would the Sonar failure have caused it to not be built?

https://github.com/openatv/enigma2/actions/runs/6436734605/job/17480658799

**Comment by jbleyel** [comment]
This change was only applied to master branch. The sonar error is not that easy to fix.

**Comment by wedebe** [comment]
What's the flow from master to image build? Up to now I've assumed that merges pushed to master are picked up for build overnight.

**Comment by jbleyel** [comment]
The 7.3 image is based on the 7.3 branch.
If you wanna test master you need to use the devel image.

`
wget -O - -q https://feeds2.mynonpublic.com/devel-feed | bash
`

**Comment by wedebe** [comment]
> The 7.3 image is based on the 7.3 branch. If you wanna test master you need to use the devel image.
> 
> `wget -O - -q https://feeds2.mynonpublic.com/devel-feed | bash`

Ah, thanks. How often/what triggers a merge of master into 7.3?

**Comment by jbleyel** [comment]
It depends.
Some things will be merged directly and some things needs to test.

**Pull request merged**
