### PR TITLE
Add embeded streamrelay functionality

### PR DESCRIPTION
**Pull request by jbleyel**
Stream relay is a function that e.g. Oscam offers and is a method where the hardware of the box is somehow not able to encrypt specific service. Streamrelay users a stream in between where the enryption is simulated in software. With this commit you can mark service refeerences stored in a whitelist /etc/enigma2/whitelist_streamrelay. When you try to tune one of these services the service ref is adapted in Navigate.py such a way that it plays the service via a stream relay server defined by two configs (IP, default local host and port default 17999). The whitelist can also be downloaded to you receiver and then you do not need special stream relay user bouquets anymore. You can also add/remove services via the channel list context menu.

Some parts are taken from this commit including some more. https://github.com/OpenPLi/enigma2/commit/3b9d7f3d9996380e338bc176534d67056d86624d

Thanks to @Littlesat

### CODE REVIEW

**Comment by norhap** [comment]
https://github.com/oscam-emu/oscam-patched/wiki/Stream-Relay-config
I have my doubts with points 5 and 6 of that wiki
Is that format embedded in the InfoBarStreamRelay class?

**Comment by jbleyel** [comment]
> https://github.com/oscam-emu/oscam-patched/wiki/Stream-Relay-config I have my doubts with points 5 and 6 of that wiki Is that format embedded in the InfoBarStreamRelay class?

The code is tested and it's working.

**Comment by littlesat** [comment]
Point 6 (and maybe also 5) need investigation and fix…. Likely oscam icam code needs a debug. Technically there is no reason why it is needed.Verstuurd vanaf mijn iPhoneOp 22 okt. 2023 om 20:23 heeft jbleyel ***@***.***> het volgende geschreven:﻿

https://github.com/oscam-emu/oscam-patched/wiki/Stream-Relay-config I have my doubts with points 5 and 6 of that wiki Is that format embedded in the InfoBarStreamRelay class?

The code is tested and it's working.

**Comment by norhap** [comment]
Correct, those are my doubts, what I have seen is always done through a list editor program, where the stream with the assigned port and port with this commitment is sent to the branches with an always fictitious format.
Service Type 1
service ID 11
Transponder ID 11
Network ID 22
Namespace 33

**Comment by norhap** [comment]
> > https://github.com/oscam-emu/oscam-patched/wiki/Stream-Relay-config I have my doubts with points 5 and 6 of that wiki Is that format embedded in the InfoBarStreamRelay class?
> 
 > The code is tested and it's working.


I understand from what I read in your class InfoBarStreamRelay that you have given the same approach as ViX fictitious reference names.
https://github.com/OpenViX/enigma2/commit/4d502e158ec7474b517b54f31b1c4ac45477b01b
That was my question.

**Comment by Ev0-BH** [comment]
> Point 6 (and maybe also 5) need investigation and fix…. Likely oscam icam code needs a debug. Technically there is no reason why it is needed.>

Point 6 is listed in the oscam-emu wiki, which is from the oscam-emu patch on that git.

So surely the reason for the dummy namespace comes from that oscam-emu patch and has nothing to do with any patches applied ontop of that ?

**Comment by norhap** [comment]
there is a wrong indent, it is also being merged wrong here, InfoBarGenerics.py https://github.com/OpenPLi/enigma2/blob/3ca9926577095870dea5c7994f8d70f8c9e25224/lib/python/Screens/InfoBarGenerics.py#L162:L164
On the other hand jbleyel this job is working fine, the only thing I have played on a receiver with FCC activated with zap up down previous and next, it complains in the toogle function in the new InfoBarStreamRelay class in the changes in playback type (with o without streamrelay)
< 3585.9650> if nav.getCurrentlyPlayingServiceReference() == service:
< 3585.9654> TypeError: in method 'eServiceReference___eq__', argument 2 of type 'eServiceReference const &'

**Comment by jbleyel** [comment]
I think you cannot use FCC and stream relay .. this os not working.

**Comment by 420Dope** [comment]
Idea or feature request:
Isn't it possible to read all services from a provider like Sky? We can show all channels from a provider if we are in the channel list and click "yellow" for provider and look the list from the provider. It looks like it is possible to know all channels from the provider so isn't it possible to check all services from the channels in the providers list?
Maybe we can have a automatism or somethink like that? After we have searched for new channels, read all services from the provider list and put it in "whitelist_streamrelay".
I mean, it is only possible to decrypt this channels with stream relay. So why not put the services from this provider automatically in the whitelist?

Maybe it is worth to think about it?

**Comment by littlesat** [comment]
Not all channels use icam....

**Comment by Ev0-BH** [comment]
It takes what 2 / 3 mins to manually add all the channels you want to use SR, or about 10 seconds to use a file that someone has already started updating on github.

As said already not all channels use icam.

**Comment by 420Dope** [comment]
> Not all channels use icam....

Yeah I know that. But look at "all these icam channel lists around the www". They have put all s*y channels in the list which are simulcrypt like "Romance TV HD", "Heimatkanal", "PULS 4 HD Austria", "eSPORTS1" regardless if they use icam or csa. So most people have already channels in their channel list which use not icam.
But nevermind, that was not my intention of the idea. It would be very user friendly and also a "nice to have" if we show us all channels from this provider with "yellow" and have a "one click" option to "Play all channels with Stream Relay". A "automatism" that that puts all channels automatically in the whitelist after a channel sreach or sometink like that would be also very nice. 


> It takes what 2 / 3 mins to manually add all the channels you want to use SR,

Yes fair point and I agree with you. It is not that "work" to put the channels in the list or copy ready icam channel list to your box as before. I think we both agree with that.
But with this "attitude", whats the point of this pull request? The answer is: convenience and comfort with the channels in all favorite lists. So why not go one step further in convenience and comfort and have these option or automatism? Isn't it that what we all want?

It was only a idea. I think there were a lot of people which find this very useful. Or is that idea totally absurd?

> or about 10 seconds to use a file that someone has already started updating on github.
> 
> As said already not all channels use icam.

Some "whitelist_streamrelay" which you can download in some boards have those csa channels in the list, so...

**Comment by jbleyel** [comment]
https://github.com/openatv/enigma2/commit/dae69c164cb6dd8b702a88b6aece1334653d5c49

**Comment by 420Dope** [comment]
> [dae69c1](https://github.com/openatv/enigma2/commit/dae69c164cb6dd8b702a88b6aece1334653d5c49)

Thank you for your work. I would give some feedback.
If we have add a complete provider list (over yellow button->Copy to Stream Relay) to Stream Relay and we later delete a single channel from Stream Relay all is ok. But if we now want to add a the same complete provider list (we have actually all channels in the whitelist until the one we have delete) to Stream Relay (over yellow button->Copy to Stream Relay), the whitelist is invertet. All channels which are before in the list are delete, and the one we have delete before is now in the list. Normally only the delete channel should be added to the list again.
Maybe there must be a check before which channels are already in the list and must not be added again and which are not in the list must be added.

Background about this funkction/option:
If there where new channels and we have made a search for new channels. We must only do "one click" with yellow button->Copy to Stream Relay and have all the needed channels in the whitelist.

**Comment by jbleyel** [comment]
That's not possible and I will not implement this.
Copy all from a provider is the only way.
Color button is also not possible.

**Comment by 420Dope** [comment]
> That's not possible and I will not implement this.

Ok, thats sad. But thanks again for your work.

> Copy all from a provider is the only way.

Is there maybe a way to delete the complete whitelist or all channels from the whitelist? So I can come to terms with that. After a channel search, delete all channels and copy all channels from the provider list.

> Color button is also not possible.

With "one click over yellow button->Copy to Stream Relay" I mean not an implemantation for a "real one click". That describes only the way with "channel list->yellow button->providerlist->menu->copy to Stream Relay" which I named "one click" :)

**Comment by littlesat** [comment]
Instead of adding the special bouquet you now also can put a whitelist on the box and then restart enigma2 and all is done.

**Pull request merged**
